---
#- name: 18. Habilitar el tráfico entrante en el cortafuegos
 # tasks: 
- name: Habilitamos los puertos necesarios para unirse al clúster 10250
  firewalld:
    port: 10250/tcp
    permanent: true
    zone: public
    state: enabled
  become: true

- name: Habilitamos los puertos necesarios para unirse al clúster 30000 32767
  firewalld:
    port: 30000-32767/tcp
    permanent: true
    zone: public
    state: enabled
  become: true
  
- name: Reiniciando el servicio Firewalld 
  systemd:
    name: firewalld
    state: restarted
  become: true

- name: 19. Añadir el worker al cluster de Kubernetes
  shell: "kubeadm join {{ ip_master }}:6443 --token {{ token_hash }} --discovery-token-ca-cert-hash sha256:{{ cert_hash }}"
  register: kubeadm_join
  become: true

- name: Resultado de la unión del Worker al clúster
  debug:
    msg: "{{ kubeadm_join.stdout_lines }}"